export {
  AffineParams3DSchema,
  backgroundColorDefault,
  backgroundColorDefaultWhite,
  BaseVariationDescriptor,
  camera3DDefault,
  type Camera3DObj,
  Camera3DObjSchema,
  condenseFlameDescriptor,
  FlameDescriptor,
  FlameDescriptor3D,
  FlameLayer,
  type FlameBlendMode,
  flameComplexityError,
  isFlameGraphWithinLimits,
  isSafeFlameEntityId,
  latestSchemaVersion,
  makeFlameDescriptorSchema,
  MAX_CAMERA_ZOOM_VALUE,
  MAX_FLAME_ENTITY_ID_LENGTH,
  MAX_FLAME_TRANSFORMS,
  MAX_FLAME_VARIATIONS,
  MAX_ORBIT_RADIUS,
  MAX_SKIP_ITERS_VALUE,
  MAX_VARIATIONS_PER_TRANSFORM,
  MIN_CAMERA_ZOOM_VALUE,
  MIN_ORBIT_RADIUS,
  RenderSettings,
  renderSettingsDefault,
  type SafeFlameEntityId,
  TransformFunction,
  TransformId,
  type TransformRecord,
  tryValidateFlame,
  validateFlame,
  validateFlame3D,
  validateFlameWithErrors,
  VariationDescriptor,
  VariationId,
} from '@chaos-master/core'
